apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: mycluster.icp:8500/ibmcom/account
        ports:
        - containerPort: 9001
        
---

apiVersion: v1
kind: Service
metadata:
 name: account
 labels:
   app: account
spec:
 ports:
 - port: 9001
   name: http
 selector:
   app: account

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: account-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api/account
        backend:
         serviceName: account
         servicePort: 9001